# Generated by Django 3.0 on 2020-11-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_customer_order_ordereditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Towar', 'verbose_name_plural': 'Towary'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamowienia'},
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'verbose_name': 'ZamówionyTowar', 'verbose_name_plural': 'ZamówioneTowary'},
        ),
    ]
