# Generated by Django 3.0.8 on 2021-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_auto_20201114_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(default='nok', max_length=50),
        ),
    ]
