# Generated by Django 3.0.8 on 2021-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_auto_20211211_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
