# Generated by Django 3.2.10 on 2022-01-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_auto_20220103_1152'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordereditem',
            constraint=models.UniqueConstraint(fields=('item', 'order'), name='unique item for order'),
        ),
    ]
