# Generated by Django 3.2.10 on 2022-01-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0011_auto_20220112_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_app.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nok', 'Not started'), ('ong', 'Ongoing'), ('pkd', 'Packed'), ('shp', 'Shipped')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(choices=[('nok', 'Not started'), ('pro', 'Produces'), ('ass', 'Assembled'), ('pkd', 'Packed')], default='nok', max_length=50, verbose_name='Status'),
        ),
    ]
